chore: testing runner on docker, exporting results

diff --git a/Dockerfile.UnitTests b/Dockerfile.UnitTests
--- a/Dockerfile.UnitTests
+++ b/Dockerfile.UnitTests
@@ -3,7 +3,7 @@ WORKDIR /app
 
 COPY . ./
 WORKDIR /app/backend
-RUN ./mvnw clean test -Dmaven.test.skip=false
+RUN ./mvnw clean test -Dmaven.test.skip=false 2>&1 | tee /tmp/test.log || echo "Tests failed"
 
 FROM scratch AS export-stage
 COPY --from=test-stage /app/backend/target/surefire-reports/TEST-*.xml /
